name: stats4hackers_py27
channels:
  - defaults
dependencies:
  - alabaster=0.7.10
  - asn1crypto=0.24.0
  - babel=2.5.3
  - backcall=0.1.0
  - bleach=2.1.3
  - ca-certificates=2018.03.07
  - certifi=2018.1.18
  - cffi=1.11.5
  - chardet=3.0.4
  - cryptography=2.2.2
  - cycler=0.10.0
  - dbus=1.13.2
  - decorator=4.2.1
  - docutils=0.14
  - entrypoints=0.2.3
  - expat=2.2.5
  - freetype=2.8
  - gettext=0.19.8.1
  - glib=2.56.1
  - html5lib=1.0.1
  - icu=58.2
  - idna=2.6
  - imagesize=1.0.0
  - intel-openmp=2018.0.0
  - ipykernel=4.8.2
  - ipython=6.3.1
  - ipython_genutils=0.2.0
  - ipywidgets=7.2.0
  - jedi=0.11.1
  - jinja2=2.10
  - jpeg=9b
  - jsonschema=2.6.0
  - jupyter=1.0.0
  - jupyter_client=5.2.3
  - jupyter_console=5.2.0
  - jupyter_core=4.4.0
  - kiwisolver=1.0.1
  - libcxx=4.0.1
  - libcxxabi=4.0.1
  - libedit=3.1
  - libffi=3.2.1
  - libgfortran=3.0.1
  - libiconv=1.15
  - libpng=1.6.34
  - libsodium=1.0.16
  - markupsafe=1.0
  - matplotlib=2.2.2
  - mistune=0.8.3
  - mkl=2018.0.2
  - mkl_fft=1.0.1
  - mkl_random=1.0.1
  - nbconvert=5.3.1
  - nbformat=4.4.0
  - ncurses=6.0
  - notebook=5.4.1
  - numpy=1.14.2
  - numpydoc=0.8.0
  - openssl=1.0.2o
  - packaging=17.1
  - pandas=0.22.0
  - pandoc=1.19.2.1
  - pandocfilters=1.4.2
  - parso=0.1.1
  - patsy=0.5.0
  - pcre=8.42
  - pexpect=4.4.0
  - pickleshare=0.7.4
  - pip=9.0.3
  - prompt_toolkit=1.0.15
  - ptyprocess=0.5.2
  - pycparser=2.18
  - pygments=2.2.0
  - pyopenssl=17.5.0
  - pyparsing=2.2.0
  - pyqt=5.9.2
  - pysocks=1.6.8
  - python=2.7
  - python-dateutil=2.7.2
  - pytz=2018.3
  - pyzmq=17.0.0
  - qt=5.9.4
  - qtconsole=4.3.1
  - readline=7.0
  - requests=2.18.4
  - scipy=1.0.1
  - seaborn=0.8.1
  - send2trash=1.5.0
  - setuptools=39.0.1
  - simplegeneric=0.8.1
  - sip=4.19.8
  - six=1.11.0
  - snowballstemmer=1.2.1
  - sphinx=1.7.2
  - sphinxcontrib=1.0
  - sphinxcontrib-websupport=1.0.1
  - sqlite=3.22.0
  - statsmodels=0.8.0
  - terminado=0.8.1
  - testpath=0.3.1
  - tk=8.6.7
  - tornado=5.0.1
  - traitlets=4.3.2
  - typing=3.6.4
  - urllib3=1.22
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - wheel=0.31.0
  - widgetsnbextension=3.2.0
  - xz=5.2.3
  - zeromq=4.2.5
  - zlib=1.2.11
prefix: /Users/croach/anaconda3/envs/stats4hackers_py27
